### PR TITLE
Fixed php 5.3 syntax error

### PR DESCRIPTION
**Pull request by 1ed**

### CODE REVIEW

**Comment by nicolasricci** [comment]
as far as I am aware array() is not deprecated in PHP 5.3. I don't really see the point of that PR. Can you tell me more?

**Comment by 1ed** [comment]
Using `[ ]` as array is a syntax error in php 5.3. It is available only from php 5.4.0.

**Comment by nicolasricci** [comment]
sorry i thought the PR was the other way round ... long day
indeed this has been added in a previous PR and I did not pay attention to it
thanks for noticing it!

**Comment by 1ed** [comment]
No problem, it happens sometimes :smile: Thanks!

**Pull request merged**
