### PR TITLE
Test if parent class is abstract in PositionHandler service

### LINKED ISSUE #73: Position field not found on MappedSuperclass
Hi,

If we use a MappedSuperclass as base class for our sortable entity, we encounter a DQL error saying there's no position field mapped on the parent class entity.

This come from the PositionORMHandler service wich does the following since commit 126204c: 
```php
while ($parentEntityClass)
{
    $parentEntityClass = ClassUtils::getParentClass($entityClass);
    if ($parentEntityClass)
        $entityClass = $parentEntityClass;
}
```
It may be necessary to check if parent class is not a MappedSuperclass.

### PR DESCRIPTION
**Pull request by baurelien**
Fix #73

### CODE REVIEW

**Comment by malenkiki** [comment]
Great PR, this fix many 500 errors in our dev since new 1.4.1.

Merge this PR quick please :-)

**Comment by koninka** [comment]
Wait for merge too

**Comment by ceesvanegmond** [comment]
👍

**Comment by baurelien** [comment]
@nicolasricci Could you please review this PR and merge it quickly ?

**Comment by nicolasricci** [comment]
@baurelien merged and new tag 1.5 released

**Pull request merged**
