### PR TITLE
check edit rights in controller and template

### PR DESCRIPTION
**Pull request by OskarStark**

### CODE REVIEW

**Comment by nicolasricci** [comment]
@OskarStark this code is only valid if working with Sonata Admin

**Comment by OskarStark** [comment]
yes, but you extend this class ```use Sonata\AdminBundle\Controller\CRUDController;````

so i'd say this is a SonataAdmin Bundle, isn't it?

**Comment by OskarStark** [comment]
and you used this:

```$id     = $this->get('request')->get($this->admin->getIdParameter());```

**Comment by nicolasricci** [comment]
my bad then, I have done this a long time ago and did not remember I was extending the SonataAdmin controller. 
Let's keep it as it is then.

**Comment by nicolasricci** [comment]
and thanks for all the changes

**Comment by OskarStark** [comment]
that is open source :smile: 

like your bundle, and it works great with sonata

**Pull request merged**
